// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzlpvnshaniwgwggohxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6bHB2bnNoYW5pd2d3Z2dvaHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzA1ODUsImV4cCI6MjA2MjEwNjU4NX0.ZQoX4fqKgaC8ryq5ZZ-n-g60QiLdYk1M-Q6gJXDVtCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);