// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mknakmwbnvyasbvunbuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rbmFrbXdibnZ5YXNidnVuYnV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDM0NzQsImV4cCI6MjA2MjAxOTQ3NH0.dCjmou1WsXU_J-zx3NxVNRpoQG_C22CFl-u80HPNUz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);